        <div class="container-fluid">

          <!-- 404 Error Text -->
          <div class="text-center">
            <div class="error mx-auto" data-text="404">404</div>
            <p class="lead text-gray-800 mb-5">Pagina Não Encontrada</p>
            <p class="text-gray-500 mb-0">Parece que você encontrou uma falha na Matrix ...</p>
            <a href="?view=Dashboard1">&larr; Voltar ao Início !</a>
          </div>

        </div>